# Generated by Django 5.2.4 on 2025-07-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_category_todo_user_alter_todo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('etc', 'Etc')], max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
